version: "3.8"
services:
  app4:
    container_name: app4
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8084:8080"
      - '5177:5177'
    networks:
      - mysql-container_mysql_network
networks:
    mysql-container_mysql_network:
        external: true
